---
application:
  name: "project-sample"
  project: "Isv project sample"
  organization: "QoveryCommunity"
routers:
- name: "main-project-sample"
  routes:
  - application_name: "project-sample"
    paths:
    - "/*"
